# Default values for proxysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: proxysql/proxysql
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306

resources: {}