apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxysql.fullname" . }}
data:
  proxysql.cnf: |
    datadir="/var/lib/proxysql"
    
    mysql_variables=
    {
        threads=8
        max_connections=2048
        default_query_delay=0
        default_query_timeout=36000000
        have_compress=true
        poll_timeout=2000
        interfaces="0.0.0.0:3306"
        default_schema="information_schema"
        stacksize=1048576
        server_version="5.6.40-log"
        connect_timeout_server=3000
        monitor_username="benchmark"
        monitor_password="benchmark"
        monitor_history=600000
        monitor_connect_interval=60000
        monitor_ping_interval=10000
        monitor_read_only_interval=1500
        monitor_read_only_timeout=500
        ping_interval_server_msec=120000
        ping_timeout_server=500
        commands_stats=true
        sessions_sort=true
        connect_retries_on_failure=10
    }


    # defines all the MySQL servers
    mysql_servers =
    (
        {
            address = "mysql" # no default, required . If     port is 0 , address is interpred as a Unix Socket Domain
            port = 3306           # no default, required . If port is 0 , address is interpred as a Unix Socket Dom    ain
            hostgroup = 0         # no default, required
            status = "ONLINE"     # default: ONLINE
            weight = 1            # default: 1
            compression = 0       # default: 0
        },
        {
            address = "mysql" # no default, required .     If port is 0 , address is interpred as a Unix Socket Domain
            port = 3306           # no default, required . If port is 0 , address is interpred as a Unix Socket Dom    ain
            hostgroup = 1         # no default, required
            status = "ONLINE"     # default: ONLINE
            weight = 1            # default: 1
            compression = 0       # default: 0
        }
    )


    # defines all the MySQL users
    mysql_users:
    (
        { username = "benchmark" , password = "benchmark" , default_hostgroup = 0 , active = 1 }
    )



    #defines MySQL Query Rules
    mysql_query_rules:
    (
        {
            rule_id=0
            active=1
            match_pattern="^\s*UPDATE (?!.[\s\S]*(where))"
            destination_hostgroup=1
            apply=0
            flagOUT=403
        },
        {
            rule_id=1
            active=1
            match_pattern="^\s*DELETE (?!.[\s\S]*(where))"
            destination_hostgroup=1
            apply=0
            flagOUT=403
        },
        {
            rule_id=2
            active=1
            match_pattern="^\s*/\*master\*/"
            destination_hostgroup=0
            apply=1
        },
        {
            rule_id=3
            active=1
            match_pattern="^\s*SELECT [\s\S]* FOR UPDATE$"
            destination_hostgroup=0
            apply=1
        },
        {
            rule_id=4
            ctive=1
            match_pattern="^\s*SELECT"
            destination_hostgroup=1
            apply=1
        },
        {
            rule_id=1001
            active=1
            apply=1
            flagIN=403
            error_msg="Query not allowed"
        }
    )

    scheduler=
    (
    )


    mysql_replication_hostgroups=
    (
    )