apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "benchmark.fullname" . }}
data:
  benchmark.sh: |
    #!/bin/bash

    echo "========== Clean Up =========="
    
    sysbench /usr/share/sysbench/{{ .Values.sysbench.target }} cleanup \
    --mysql-host=mysql \
    --mysql-user=benchmark \
    --mysql-password=benchmark \
    --mysql-db=benchmark

    echo "========== Prepare =========="

    sysbench /usr/share/sysbench/{{ .Values.sysbench.target }} prepare \
    --table_size=10000 \
    --mysql-host=mysql \
    --mysql-user=benchmark \
    --mysql-password=benchmark \
    --mysql-db=benchmark

    echo "========== Warm Up =========="
    
    sysbench /usr/share/sysbench/{{ .Values.sysbench.target }} run \
    --mysql-host=mysql \
    --mysql-user=benchmark \
    --mysql-password=benchmark \
    --mysql-db=benchmark \
    --threads=1 \
    --time=10

    sysbench /usr/share/sysbench/{{ .Values.sysbench.target }} run \
    --mysql-host=proxysql \
    --mysql-user=benchmark \
    --mysql-password=benchmark \
    --mysql-db=benchmark \
    --threads=1 \
    --time=10

    echo "========== Benchmark Start =========="

    threads=(10 50 100 500 1000 2000)
    for num in "${threads[@]}"
    do
      echo "========== MySQL Threads ${num} =========="
      
      sysbench /usr/share/sysbench/{{ .Values.sysbench.target }} run \
      --mysql-host=mysql \
      --mysql-user=benchmark \
      --mysql-password=benchmark \
      --mysql-db=benchmark \
      --threads=$num \
      --rate={{ .Values.sysbench.rate }} \
      --time={{ .Values.sysbench.time }}
      

      echo "========== ProxySQL Threads ${num} =========="

      sysbench /usr/share/sysbench/{{ .Values.sysbench.target }} run \
      --mysql-host=proxysql \
      --mysql-user=benchmark \
      --mysql-password=benchmark \
      --mysql-db=benchmark \
      --threads=$num \
      --rate={{ .Values.sysbench.rate }} \
      --time={{ .Values.sysbench.time }}
    done